/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('music').del()
  await knex('music').insert([
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees.jpeg',
    },
    {
      id: 2,
      artist: 'A Tribe Called Quest',
      album: 'Low End Theory',
      year: '1991',
      genre: 'hip-hop/rap',
      description: '',
      price: 60,
      quantity: '3',
      image_path: '/music/ATCQ-low-end-theory-back.jpeg',
    },
    {
      id: 3,
      artist: 'Blu & Exile',
      album: 'Below the Heavens',
      year: '2007',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '5',
      image_path: '/music/blu-exile-below-the-heavens-front.jpeg',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: '',
      price: 47,
      quantity: '10',
      image_path: '/music/abc-trees',
    },
  ])
}
