/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('music').del()
  await knex('music').insert([
    {
      id: 1,
      artist: 'Avantdale Bowling Club',
      album: 'Trees',
      year: '2022',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 47,
      quantity: '10',
    },
    {
      id: 2,
      artist: 'A Tribe Called Quest',
      album: 'Low End Theory',
      year: '1991',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 60,
      quantity: '3',
    },
    {
      id: 3,
      artist: 'Blu & Exile',
      album: 'Below the Heavens',
      year: '2007',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 47,
      quantity: '5',
    },
    {
      id: 4,
      artist: 'Ivan Ave',
      album: 'Double Goodbyes',
      year: '2020',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 47,
      quantity: '10',
    },
    {
      id: 5,
      artist: 'J Dilla',
      album: 'Donuts',
      year: '2006',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 59,
      quantity: '5',
    },
    {
      id: 6,
      artist: 'Kofi Stone',
      album: 'Nobody Cares Till Everybody Does',
      year: '2019',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 44,
      quantity: '5',
    },
    {
      id: 7,
      artist: 'Little Brother',
      album: 'The Listening',
      year: '2003',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 54,
      quantity: '10',
    },
    {
      id: 8,
      artist: 'Nas',
      album: 'Illmatic',
      year: '1994',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 47,
      quantity: '3',
    },
    {
      id: 9,
      artist: 'People Under The Stairs',
      album: 'O.S.T',
      year: '2002',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 58,
      quantity: '2',
    },
    {
      id: 10,
      artist: 'Royal Flush',
      album: 'Ghetto Millionaire',
      year: '1997',
      genre: 'hip-hop/rap',
      description: 'description',
      price: 47,
      quantity: '1',
    },
    {
      id: 11,
      artist: 'Amen Dunes',
      album: 'Freedom',
      year: '2018',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 47,
      quantity: '10',
    },
    {
      id: 12,
      artist: 'Beach Fossils',
      album: 'Somersault',
      year: '2017',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 47,
      quantity: '7',
    },
    {
      id: 13,
      artist: 'Do Nothing',
      album: 'Zero Dollar Bill',
      year: '2020',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 47,
      quantity: '4',
    },
    {
      id: 14,
      artist: 'Floodlights',
      album: 'From a View',
      year: '2020',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 42,
      quantity: '5',
    },
    {
      id: 15,
      artist: 'Fontaines D.C.',
      album: 'Dogrel',
      year: '2019',
      genre: 'Post-punk',
      description: 'description',
      price: 47,
      quantity: '7',
    },
    {
      id: 16,
      artist: 'Idles',
      album: 'Joy as an Act of Resistance',
      year: '2018',
      genre: 'Punk Rock',
      description: 'description',
      price: 47,
      quantity: '7',
    },
    {
      id: 17,
      artist: 'Parquet Courts',
      album: 'Light Up Gold',
      year: '2012',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 47,
      quantity: '4',
    },
    {
      id: 18,
      artist: 'Parquet Courts',
      album: 'Wide Awake',
      year: '2018',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 47,
      quantity: '7',
    },
    {
      id: 19,
      artist: 'The Slingers',
      album: 'One More Day / This Time',
      year: '2017',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 35,
      quantity: '3',
    },
    {
      id: 20,
      artist: 'Yard Act',
      album: 'The Overload',
      year: '2022',
      genre: 'Indie/Alternative',
      description: 'description',
      price: 47,
      quantity: '7',
    },
  ])
}
